# Generated by Django 2.2.5 on 2020-01-15 07:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.TextField()),
                ('plays', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None)),
                ('pauses', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None)),
                ('transcripts', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
                ('transcript_times', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None), size=None)),
                ('bookmarks', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None)),
            ],
        ),
    ]
