# Generated by Django 2.2.5 on 2020-01-16 04:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pauses', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='13:20'), blank=True, null=True, size=None)),
                ('bookmarks', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
    ]
