# Generated by Django 2.2.5 on 2020-01-15 07:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='plays',
        ),
        migrations.AlterField(
            model_name='session',
            name='bookmarks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True), size=None),
        ),
        migrations.AlterField(
            model_name='session',
            name='pauses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True), size=None),
        ),
        migrations.AlterField(
            model_name='session',
            name='transcript_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='session',
            name='transcripts',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None), size=None),
        ),
    ]
