# Generated by Django 2.2.5 on 2020-01-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200115_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sessionID',
            field=models.TextField(blank=True),
        ),
    ]
