# Generated by Django 2.2.5 on 2020-01-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200115_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='session',
            name='pauses',
        ),
        migrations.RemoveField(
            model_name='session',
            name='transcript_times',
        ),
        migrations.RemoveField(
            model_name='session',
            name='transcripts',
        ),
    ]
